trigger:
- '*'

variables:
  buildConfiguration: 'Release'
  dotnetSdkVersion: '5.x'

stages:
- stage: 'Test'
  displayName: 'Run the Selenium tests'
  jobs:
  - job: RunUITests
    displayName: 'Run UI tests'
    pool:
      vmImage: 'windows-2019'



    steps: 
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)' # Update this to match your need)'
    - task: DotNetCoreCLI@2
      displayName: 'Run unit tests - $(buildConfiguration)'
      inputs:
        command: 'test'
        publishTestResults: true
       

